name: Memory Safety and Security Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-and-safety:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Rust (nightly)
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true

    - name: Install Clippy
      run: rustup component add clippy

    - name: Install Rustfmt
      run: rustup component add rustfmt

    - name: Install Miri
      run: rustup component add miri

    - name: Install Cargo Audit
      run: cargo install cargo-audit

    - name: Run Clippy (Linter)
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Run Rustfmt (Code Formatting)
      run: cargo fmt --all -- --check

    - name: Run Miri (Memory Safety Checker)
      run: cargo miri run --all-targets

    - name: Run Security Audits
      run: cargo audit

